library(tidyverse)
data(starwars)
starwars %>% select(-name)
starwars %>% select(contains("_"))
starwars %>% select(starts_with("s"))
homeworld <- starwars %>% select(name, homeworld)
human <- starwars %>% filter(species == "Human")
starwars %>% filter(species == "Human", homeworld == "Tatooine")
starwars_nodroids <- starwars %>% filter(species != "Droid")
#¿Cuántos registros cumplen las condiciones finales? En homeworld 87, ya que no hay ninguno del que no se pueda sacar nombre y homeworld, en el de human 35 y nondroids 77.
starwars %>% group_by(species) %>% tally()
starwars %>% group_by(species, gender) %>% tally()
table_gender <- starwars %>% group_by(species, gender) %>% tally()
starwars %>% group_by(species) %>% summarise(mean_height = mean(height, na.rm = T),mean_mass = mean(mass,na.rm = T))
?sd
sd(starwars %>% group_by(species) %>% summarise(mean_height = mean(height, na.rm = T),mean_mass = mean(mass,na.rm = T)), na.rm = FALSE)
starwars %>% group_by(species) %>% summarise(sd_height = sd(height, na.rm = FALSE),sd_mass = sd(mass,na.rm = FALSE))
starwars %>% group_by(species) %>% summarise(sd_height = sd(height, na.rm = T),sd_mass = sd(mass,na.rm = T))
#¿Cómo calcularías la desviación estándar (sd) de esos parámetros? starwars %>% group_by(species) %>% summarise(sd_height = sd(height, na.rm = T),sd_mass = sd(mass,na.rm = T))
ggplot(starwars, aes(height, mass)) + geom_point()
ggplot(starwars, aes(height, mass)) + geom_point(colour = "red")
ggplot(starwars, aes(height, mass)) + geom_point(colour = "purple", pch = 3)
ggplot(starwars, aes(height, mass)) + geom_point(colour = "red") + theme_light(colour = "purple")
mass_sin_jabba <- starwars %>% filter(name != "Jabba Desilijic Tiure")
#ejercicio3: mass_sin_jabba <- starwars %>% filter(name != "Jabba Desilijic Tiure")
ggplot(mass_sin_jabba, aes(height, mass)) + geom_point()
toy <- read_csv("toy.csv")
toy %>% group_by(Sex) %>% summarise(mean_Weight_kg = mean(Weight_Kg, na.rm = T),mean_Height_cm = mean(Height_cm,na.rm = T),mean_IMC = mean(IMC,na.rm = T),mean_IAS = mean(IAS,na.rm = T),mean_Ccintura = mean(Ccintura,na.rm = T))
women <- toy %>% filter(Sex == "Women")
women_overweight <- women %>% filter(IMC_clas == "Overweight")
#Haz una tabla sólo con los pacientes femeninos ¿Cuántos registros cumplen las condiciones? ¿De estos cuantos tienen Sobrepeso (Overweight)?  En la tabla de mujeres hay 58 y de estas con sobrepeso 9.
ggplot(toy, aes(IMC, Weight_Kg)) + geom_point()
toy_overwight_obesity <- toy %>% filter(IMC_clas != "Normal")
ggplot(toy_overwight_obesity, aes(IMC, Weight_Kg)) + geom_point()
install.packages("ape")
install.packages("phangorn")
install.packages("phytools")